# Generated by Django 6.1 on 2026-08-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_room_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
